# H2 Database Setup (No download needed!)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.data.mongodb.uri=mongodb+srv://<username>:chakradhar9090@cluster0.xxxx.mongodb.net/taskdb?retryWrites=true&w=majority