# Database Connection
spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb+srv://chakradhar:chakradhar1111@cluster0.uryigy1.mongodb.net/taskdb?retryWrites=true&w=majority

# Server Port
server.port=${PORT:8080}

# Clean JSON Output
spring.jackson.serialization.indent_output=true
